# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tts.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ttts.proto\x12\x05order\"\x1a\n\nTTSrequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1c\n\x0bTTSresponse\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\x32\x44\n\nTTSservice\x12\x36\n\rGenerateAudio\x12\x11.order.TTSrequest\x1a\x12.order.TTSresponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TTSREQUEST']._serialized_start=20
  _globals['_TTSREQUEST']._serialized_end=46
  _globals['_TTSRESPONSE']._serialized_start=48
  _globals['_TTSRESPONSE']._serialized_end=76
  _globals['_TTSSERVICE']._serialized_start=78
  _globals['_TTSSERVICE']._serialized_end=146
# @@protoc_insertion_point(module_scope)
